name: habits
description: "Let's Habit"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flex_color_scheme: ^8.0.2
  signals: ^6.0.2
  fluttermoji: ^1.0.2
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  get_it: ^8.0.2
  ionicons: ^0.2.2
  diacritic: ^0.1.6
  auto_size_text: ^3.0.0
  intl: ^0.20.1
  synchronized: ^3.3.0+3
  http: ^1.2.2
  logging: ^1.3.0
  sqflite: ^2.4.1
  path: 1.9.0
  collection: ^1.18.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_channel_ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0A5BA3"
  adaptive_icon_foreground: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#0A5BA3"
    theme_color: "#0A5BA3"
  windows:
    generate: true
    image_path: "assets/icon/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
    image_path_macos: "assets/icon/app_icon.png"
    remove_alpha_ios: true